"""empty message

Revision ID: 7cb3c7bd0747
Revises: 6cfae8e7b693
Create Date: 2025-05-28 13:23:31.410682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cb3c7bd0747'
down_revision = '6cfae8e7b693'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cripto_prediction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cripto_name', sa.String(length=50), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('actual_price', sa.Float(), nullable=False),
    sa.Column('predicted_price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_constraint('news_urlToImage_key', type_='unique')
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.drop_column('urlToImage')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('urlToImage', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('news_urlToImage_key', ['urlToImage'], postgresql_nulls_not_distinct=False)

    op.drop_table('cripto_prediction')
    # ### end Alembic commands ###
