"""empty message

Revision ID: b35a3af0bfe4
Revises: 94e9f08c9954
Create Date: 2025-05-31 16:33:02.612349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b35a3af0bfe4'
down_revision = '94e9f08c9954'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crypto_price', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_prediction', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crypto_price', schema=None) as batch_op:
        batch_op.drop_column('is_prediction')

    # ### end Alembic commands ###
